Repository eclipse-edc/RegistrationService, pull requests merged in 2022-11, with the labels that each got.

#54 refactor(buld): apply the edc build plugin
  build.gradle.kts
  client-cli/build.gradle.kts
  extensions/participant-verifier/build.gradle.kts
  extensions/registration-policy-gaiax-member/build.gradle.kts
  extensions/registration-service/build.gradle.kts
  extensions/store/cosmos/participant-store-cosmos/build.gradle.kts
  extensions/store/sql/participant-store-sql/build.gradle.kts
  gradle.properties
  launcher/build.gradle.kts
  rest-client/build.gradle.kts
  settings.gradle.kts
  spi/dataspace-authority-spi/build.gradle.kts
  spi/participant-store-spi/build.gradle.kts
  system-tests/build.gradle.kts
  system-tests/launchers/identity-hub/build.gradle.kts
Labels: enhancement

#56 chore: use standard version property
  build.gradle.kts
Labels: refactoring

#58 chore: use SNAPSHOT version of EDC
  .github/workflows/verify.yaml
  gradle.properties
  settings.gradle.kts
  system-tests/docker-compose.yml
  system-tests/launchers/participant/Dockerfile
  system-tests/launchers/participant/build.gradle.kts
Labels: build
